### ISSUE TITLE
시간/분별 시세 데이터 (OHLCV) 제공 여부

### ISSUE THREAD

**Issue by pjueon** [koreainvestment/open-trading-api#11]
안녕하세요
 
[KIS Developers](https://apiportal.koreainvestment.com/apiservice/apiservice-domestic-stock-quotations#L_07802512-4f49-4486-91b4-1050b6f5dc9d) 상의 문서를 보면 일/주/월/년 별 시세 데이터 조회만 나와있는데

시간/분별 시세 데이터 제공이 가능한지 문의드립니다.

**Comment by koreainvestment** [comment]
안녕하세요
KIS Developers입니다.

답변이 늦어 죄송합니다.

시간별 시세 데이터는 준비되지 않았으며, 국내주식시세 > 주식당일분봉조회 API로 당일에 한하여 분봉 조회는 가능합니다.
주식당일분봉조회 API 실전계좌/모의계좌의 경우, 한 번의 호출에 최대 30건까지 확인 가능합니다.
자세한 사항은 KIS Developers 홈페이지 - API문서 확인 부탁드립니다.

추가적인 문의사항이 있으시면 언제든 문의 부탁드립니다.
감사합니다.

**Comment by pjueon** [comment]
답변 감사합니다. 시간별 시세 데이터도 추후 추가되길 희망해봅니다.
