### ISSUE TITLE
openapi 스팩 json 문서를 공유할 수 있나요?

### ISSUE THREAD

**Issue by mrchypark** [koreainvestment/open-trading-api#2]
openapi 스팩 문서를 공유해주시면, 많은 언어에서 클라이언트 패키지를 쉽게 만드는데 사용할 수 있을 것 같습니다.

**Comment by koreainvestment** [comment]
json 문서가 따로 준비된 사항이 없습니다.

필요하시다면 준비할 수 있도록 검토해보겠습니다.

혹시 어떠한 형태가 필요하신가요

**Comment by mrchypark** [comment]
https://apiportal.koreainvestment.com/apiservice/oauth2#L_214b9e22-8f2e-4fba-9688-587279f1061a

위 링크를 보건데 따로 문서를 어떤 것이든 양식에 맞춰서 생산하신 것으로 이해했습니다. openapi v3이 가장 많이 사용하는 양식으로 저는 이해하고 있구요. 그래서 위 문서를 생성하실 때 어떤 표준 문서 양식을 기준으로 생성하시지 않았을까 가정하였습니다.

openapi는 스펙 작성을 json 형식으로 하기 때문에 문의 드렸습니다. 혹시 어떤 표준 양식을 사용하시지 않고 따로 위에 문서 페이지를 만든 것이시라면 알려주세요. 

감사합니다.

**Comment by binsoore** [comment]
기존 대신증권 크레온에서 OHLC 를 지원했는데 
( 20일 평균, 60일 평균으로 매수, 매도전략을 구할려고 ) 

앞으로 지원 가능할까요?

크레온 Python 예제) 

def get_ohlc(code, qty):
    """인자로 받은 종목의 OHLC 가격 정보를 qty 개수만큼 반환한다."""
    cpOhlc.SetInputValue(0, code)           # 종목코드
    cpOhlc.SetInputValue(1, ord('2'))        # 1:기간, 2:개수
    cpOhlc.SetInputValue(4, qty)             # 요청개수
    cpOhlc.SetInputValue(5, [0, 2, 3, 4, 5]) # 0:날짜, 2~5:OHLC
    cpOhlc.SetInputValue(6, ord('D'))        # D:일단위
    cpOhlc.SetInputValue(9, ord('1'))        # 0:무수정주가, 1:수정주가
    cpOhlc.BlockRequest()
    count = cpOhlc.GetHeaderValue(3)   # 3:수신개수
    columns = ['open', 'high', 'low', 'close']
    index = []
    rows = []
    for i in range(count): 
        index.append(cpOhlc.GetDataValue(0, i)) 
        rows.append([cpOhlc.GetDataValue(1, i), cpOhlc.GetDataValue(2, i),
            cpOhlc.GetDataValue(3, i), cpOhlc.GetDataValue(4, i)]) 
    df = pd.DataFrame(rows, columns=columns, index=index) 
    return df

**Comment by koreainvestment** [comment]
따로 위의 문서 페이지를 제작했습니다.
스펙 작성을 json형태로 변환할 수 있을지 검토해보겠습니다.

**Comment by mrchypark** [comment]
@koreainvestment 이해했습니다. 그 전까지는 포털의 문서를 참고하겠습니다. 
저의 질문은 모두 해결되었습니다.
감사합니다.

**Comment by mrchypark** [comment]
@koreainvestment openapi와 swagger는 같은 말입니다만, 혹시 알고 계신가요? 테스트베트가 swagger로 되어 있길래 추가 질문 드립니다.

![image](https://user-images.githubusercontent.com/6179259/178522610-ae9b47e6-fa2a-4b52-9ff7-be1950da09ca.png)

**Comment by justinyoo** [comment]
적어도 여기 소스코드를 보면 OpenAPI 문서가 있을 것 같습니다.

https://github.com/koreainvestment/open-trading-api/blob/5bd3c00be14a00ff5d2094cf05e19ba014d656de/rest/kisdev_vi.yaml#L17-L20

**Comment by koreainvestment** [comment]
감사합니다. 말씀해주신 내용도 준비 중에 있습니다. 완료되면 공지하겠습니다.

**Comment by jdlee726** [comment]
https://openapi.koreainvestment.com:9443/swagger-ui.html 페이지를 보니, springfox 2.9.2 를 사용하고 있는 듯 합니다.
springfox 는  일반적으로 ${base_url}/v2/api-docs 를 통해, https://editor.swagger.io/ 에서 편집할 수 있는 swagger spec 문서를 제공해 줄 수 있습니다. swagger spec 문서만 있으면, 임의의 클라이언트 (java, python, javascript, typescript 등)를 매우 쉽게 생성할 수 있습니다.
따라서, 위 swagger spec 문서를 제공하는 ${base_url} 이 있다면, 이 것만 알려주시면 많은 클라이언트 개발자들에게 큰 도움이 될 것으로 생각됩니다.
