### ISSUE TITLE
한투증권 API 신청할려는데 맥에서 로그인이 안됨

### ISSUE THREAD

**Issue by sunglim** [koreainvestment/open-trading-api#21]
무슨 설치를 계속하라고 하네요  재부팅도 해봤습니다

일단 로그인부터되게 하고 API를 신청을 받던가해야지... 

<img width="1265" alt="image" src="https://github.com/koreainvestment/open-trading-api/assets/756988/13c38988-9b9a-4432-8554-420cf805a081">

**Comment by pilkyuchoi** [comment]
같은 증상입니다! 혹시 해결하셨나요?

**Comment by sunglim** [comment]
피씨방가서 윈도우피씨로 로그인 하여서 신청하였습니다

2023년 7월 17일 (월) 오후 10:39, Pilkyu Choi ***@***.***>님이 작성:

**Comment by sunglim** [comment]
I'll close as 'won't fix'
