### ISSUE TITLE
해외주식 주문시 시장가 설정

### ISSUE THREAD

**Issue by pjueon** [koreainvestment/open-trading-api#6]
해외주식 주문에서 시장가로 매수/매도하려면 "주문구분(ORD_DVSN)"을 어떻게 설정해야하나요?
기존 국내주식 매매처럼 "01"로 설정시 "주문구분 입력오류입니다."라는 에러가 발생하고 
[KIS Developers의 API 문서](https://apiportal.koreainvestment.com/apiservice/apiservice-overseas-stock)를 확인했으나 해당 내용을 찾지 못하여 문의드립니다.

**Comment by pjueon** [comment]
@mingi3314 
확인 부탁드립니다

**Comment by mingi3314** [comment]
안녕하세요. 해외주식 시장가 주문은 현재 지원하지 않는 것으로 보입니다.

QnA 답변이 도움이 될까 하여 함께 첨부드립니다 : )


![image](https://user-images.githubusercontent.com/68267535/185926698-e357129e-7448-471c-81fa-b06b65fbc48f.png)

**Comment by pjueon** [comment]
답변 감사합니다. 추후 지원되면 좋겠네요.
